

kafka-producer:
  brokers:
  - 127.0.0.1:9092

kafka-consumer:
  zookeeper:
    hosts:
      - localhost
    port: 2181
  group: test
  partitions:
    hello-world: 1
  rebalanceRetries: 5
  retryResetDelay: 3 seconds

